WFI_MODE_WIM = "WIM"
WFI_MODE_WSM = "WSM"

WFI_MODES = {WFI_MODE_WIM, WFI_MODE_WSM}

WFI_DETECTORS = {
    "WFI01",
    "WFI02",
    "WFI03",
    "WFI04",
    "WFI05",
    "WFI06",
    "WFI07",
    "WFI08",
    "WFI09",
    "WFI10",
    "WFI11",
    "WFI12",
    "WFI13",
    "WFI14",
    "WFI15",
    "WFI16",
    "WFI17",
    "WFI18",
}

WFI_FRAME_TIME = {WFI_MODE_WIM: 3.04,
                  WFI_MODE_WSM: 4.03}


WFI_P_EXPTYPE_IMAGE = "WFI_IMAGE|"
WFI_P_EXPTYPE_GRISM = "WFI_GRISM|"
WFI_P_EXPTYPE_PRISM = "WFI_PRISM|"


WFI_PEDIGREE = {"GROUND", "MODEL", "DUMMY", "SIMULATION"}


WFI_REF_OPTICAL_ELEMENT_DARK = "DARK"
WFI_REF_OPTICAL_ELEMENT_F062 = "F062"
WFI_REF_OPTICAL_ELEMENT_F087 = "F087"
WFI_REF_OPTICAL_ELEMENT_F106 = "F106"
WFI_REF_OPTICAL_ELEMENT_F129 = "F129"
WFI_REF_OPTICAL_ELEMENT_F146 = "F146"
WFI_REF_OPTICAL_ELEMENT_F158 = "F158"
WFI_REF_OPTICAL_ELEMENT_F184 = "F184"
WFI_REF_OPTICAL_ELEMENT_F213 = "F213"
WFI_REF_OPTICAL_ELEMENT_GRISM = "GRISM"
WFI_REF_OPTICAL_ELEMENT_PRISM = "PRISM"

WFI_REF_OPTICAL_ELEMENTS = {
    WFI_REF_OPTICAL_ELEMENT_DARK,
    WFI_REF_OPTICAL_ELEMENT_F062,
    WFI_REF_OPTICAL_ELEMENT_F087,
    WFI_REF_OPTICAL_ELEMENT_F106,
    WFI_REF_OPTICAL_ELEMENT_F129,
    WFI_REF_OPTICAL_ELEMENT_F146,
    WFI_REF_OPTICAL_ELEMENT_F158,
    WFI_REF_OPTICAL_ELEMENT_F184,
    WFI_REF_OPTICAL_ELEMENT_F213,
    WFI_REF_OPTICAL_ELEMENT_GRISM,
    WFI_REF_OPTICAL_ELEMENT_PRISM
}

# TODO verify the values
WFI_REF_TYPES = {
    "DARK": "DARK",
    "DISTORTION": "DISTORTION",
    "FLAT": "FLAT",
    "GAIN": "GAIN",
    "INVERSELINEARITY": "INVERSELINEARITY",
    "IPC": "IPC",
    "LINEARITY": "LINEARITY",
    "MASK": "MASK",
    "PIXELAREA": "PIXELAREA",
    "READNOISE": "READNOISE",
    "REF_COMMON": "REF_COMMON",
    "REF_EXPOSURE_TYPE": "REF_EXPOSURE_TYPE",
    "REF_OPTICAL_ELEMENT": "REF_OPTICAL_ELEMENT",
    "REFPIX": "REFPIX",
    "SATURATION": "SATURATION",
    "SUPERBIAS": "SUPERBIAS",
    "WFI_IMG_PHOTOM": "WFI_IMG_PHOTOM",
}

WFI_TYPE_IMAGE = "WFI_IMAGE"
WFI_TYPE_GRISM = "WFI_GRISM"
WFI_TYPE_PRISM = "WFI_PRISM"

WFI_TYPES = {WFI_TYPE_IMAGE, WFI_TYPE_GRISM, WFI_TYPE_PRISM}