from quality_control_config imoprt dark_quality_controls


class DarkQualityControl:

    def __init__(self,
                 rfp_dark
                 ):
        """

        rfp_dark: object
            Reference File Pipeline object created from ref_type data model and generated by the RFP
            after populate_data_model()
        check_all: boolean; default = True
            Flag to perform all quality control checks.

        """
        self.rfp_dark_meta = rfp_dark.meta
        self.rfp_dark_data = rfp_dark.data
        self.dark_qc_reference_dict = None  # Dictinary of reference keys and values
        self.check_flags = None  # Append flag or make flags with names of checks for Boolean
            # check_mean_dark_rate_flag = True means perform this check

        self.checks_results_dict = {}  # Empty dictionary of check functions executed and results

    def get_metrics
        """
        Get the keys and values of QC references from config file and/or rtbdb
        """
        self.check_flags = get_flags()
        dark_qc_reference_dict = get_reference_dict()

    def do_checks
        """
        Get check method names and flags for reference type QC and perform check if True
        """
        for check in check_flags:
            if check
                execute check
                self.check_mean_dark_rate()
                self.check_med_dark_rate()
                self.check_std_dark_rate()
                self.check_number_hot_pixels()
                self.check_number_warm_pixels()
                self.check_number_unreliable_pixels()

    def check_mean_dark_rate(self):
        """
        If this method is called, do the calculation on the data and then compare to appropriate reference key and value
        Populate a dictionary with checks run and their results
        """

        rfp_dark_mean_rate = np.mean(self.rfp_dark_data)  # Assuming rfp_dark_data is a numpy array
        logging info ('mean dark rate for {ref_type} detector{} mode{} is x.xxx dn/s')
        ref = dark_qc_referebce_dict{  max_mean_dark_rate_reference_value: value}
        logging info (Compared to value for detector WFIxx)
        if rfp_dark_mean_rate < ref
            # put the check method name and the result in a dictionary
            self.checks_results_dict.append(self.__class__.__name__: True)
        else
            self.checks_results_dict.append(self.__class__.__name__: False)

    def qc_checks_notifications
        # If all check_results_dict passed True, then return True, then ok to deliver in pipeline
        # If any are False, send slack notification yellow if marginal fail, continute delivery in pipeline
        # If multiple False, send slack notification red for failed delivery, halt delivery
        return True

    def send_results_to_rtdb

    def Update_reference_table_in_rtbdb


